---
kind: pipeline
type: kubernetes
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: test
  image: golang:1.14.4
  commands:
  - go test ./...
  
- name: build
  image: golang:1.14.4
  commands:
  - sh scripts/build.sh
  environment:
    GOARCH: amd64
    GOOS: linux

- name: publish
  image: wunderai/drone-kaniko:14
  commands:
  - /kaniko/plugin.sh
  settings:
    auto_tag: false
    auto_tag_suffix: ${DRONE_BRANCH}
    cache: false
    dockerfile: docker/Dockerfile.server.linux.amd64
    destination_prefix: waiwunderci.azurecr.io/
    username: waiwunderci
    password:
      from_secret: docker_password
    registry: waiwunderci.azurecr.io
    repo: drone
    tags:
    - ${DRONE_COMMIT_SHA:0:8}
    - ${DRONE_BRANCH}-${DRONE_BUILD_NUMBER}
  when:
    event:
    - push
    - tag

#- name: publish
#  image: plugins/docker:18
#  settings:
#    auto_tag: true
#    auto_tag_suffix: linux-amd64
#    dockerfile: docker/Dockerfile.server.linux.amd64
#    repo: wunderai/drone
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#  when:
#    event:
#    - push
#    - tag

#---
#kind: pipeline
#type: docker
#name: linux-arm64
#
#platform:
#  arch: arm64
#  os: linux
#
#steps:
#- name: build
#  image: golang:1.14.4
#  commands:
#  - sh scripts/build.sh
#  environment:
#    GOARCH: arm64
#    GOOS: linux
#
#- name: publish
#  image: plugins/docker:18
#  settings:
#    auto_tag: true
#    auto_tag_suffix: linux-arm64
#    dockerfile: docker/Dockerfile.server.linux.arm64
#    repo: drone/drone
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#
#trigger:
#  event:
#  - push
#  - tag
#
#depends_on:
#- linux-amd64
#
#---
#kind: pipeline
#type: docker
#name: linux-arm
#
#platform:
#  arch: arm
#  os: linux
#
#steps:
#- name: build
#  image: golang:1.14.4
#  commands:
#  - sh scripts/build.sh
#  environment:
#    GOARCH: arm
#    GOOS: linux
#
#- name: publish
#  image: plugins/docker:18
#  settings:
#    auto_tag: true
#    auto_tag_suffix: linux-arm
#    dockerfile: docker/Dockerfile.server.linux.arm
#    repo: drone/drone
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#
#trigger:
#  event:
#  - push
#  - tag
#
#depends_on:
#- linux-amd64
#
#---
#kind: pipeline
#type: docker
#name: manifest
#
#steps:
#- name: publish
#  image: plugins/manifest:1.2
#  settings:
#    auto_tag: true
#    ignore_missing: true
#    spec: docker/manifest.server.tmpl
#    username:
#      from_secret: docker_username
#    password:
#      from_secret: docker_password
#
#trigger:
#  event:
#  - push
#  - tag
#
#depends_on:
#- linux-arm64
#- linux-arm
#